### ISSUE TITLE
Similar names

### ISSUE THREAD

**Issue by tleen** [ilkeryilmaz/timelinejs#1]
An FYI before you publicise this too much, it has more-or-less the same name as another very popular JavaScript based timeline script: [TimelineJS](https://github.com/NUKnightLab/TimelineJS). This name is going to potentially confuse a lot of people.

**Comment by ilkeryilmaz** [comment]
Yes you are right. I gave it a name without research, it was a mistake. I plan to make improvements by focusing on different features and simple use. Things like this can make a difference for parsing. Do you have any suggestions?

Thank you for your interest.

**Comment by tleen** [comment]
Its actually tough because there are so many JavaScript things out there now. Most basic names are taken. Off the cuff: linesoftime, chronopoints? Just a quick search and almost every other name I could think of (chronoline, different anagrams) are taken!
